init:
  - git config --global core.autocrlf true
branches:
  only:
    - master
    - release
    - dev
    - feature/dev-si
    - /^(.*\/)?ci-.*$/
build_script:
  - build.cmd --quiet verify
clone_depth: 1
test: off
deploy: off
os: Visual Studio 2017 RC
